/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLog {
    #[serde(rename = "changeType", skip_serializing_if = "Option::is_none")]
    pub change_type: Option<String>,
    #[serde(rename = "changeDate", skip_serializing_if = "Option::is_none")]
    pub change_date: Option<String>,
    #[serde(rename = "objectType", skip_serializing_if = "Option::is_none")]
    pub object_type: Option<ObjectType>,
    #[serde(rename = "objectId", skip_serializing_if = "Option::is_none")]
    pub object_id: Option<uuid::Uuid>,
    #[serde(rename = "changedBy", skip_serializing_if = "Option::is_none")]
    pub changed_by: Option<String>,
    #[serde(rename = "reasonCode", skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(rename = "userToken", skip_serializing_if = "Option::is_none")]
    pub user_token: Option<String>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Box<models::Entity>>,
}

impl AuditLog {
    pub fn new() -> AuditLog {
        AuditLog {
            change_type: None,
            change_date: None,
            object_type: None,
            object_id: None,
            changed_by: None,
            reason_code: None,
            comments: None,
            user_token: None,
            history: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ObjectType {
    #[serde(rename = "ACCOUNT")]
    Account,
    #[serde(rename = "ACCOUNT_EMAIL")]
    AccountEmail,
    #[serde(rename = "BLOCKING_STATES")]
    BlockingStates,
    #[serde(rename = "BUNDLE")]
    Bundle,
    #[serde(rename = "CUSTOM_FIELD")]
    CustomField,
    #[serde(rename = "INVOICE")]
    Invoice,
    #[serde(rename = "PAYMENT")]
    Payment,
    #[serde(rename = "TRANSACTION")]
    Transaction,
    #[serde(rename = "INVOICE_ITEM")]
    InvoiceItem,
    #[serde(rename = "INVOICE_PAYMENT")]
    InvoicePayment,
    #[serde(rename = "SUBSCRIPTION")]
    Subscription,
    #[serde(rename = "SUBSCRIPTION_EVENT")]
    SubscriptionEvent,
    #[serde(rename = "SERVICE_BROADCAST")]
    ServiceBroadcast,
    #[serde(rename = "PAYMENT_ATTEMPT")]
    PaymentAttempt,
    #[serde(rename = "PAYMENT_METHOD")]
    PaymentMethod,
    #[serde(rename = "TAG")]
    Tag,
    #[serde(rename = "TAG_DEFINITION")]
    TagDefinition,
    #[serde(rename = "TENANT")]
    Tenant,
    #[serde(rename = "TENANT_KVS")]
    TenantKvs,
}

impl Default for ObjectType {
    fn default() -> ObjectType {
        Self::Account
    }
}

