/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkSubscriptionsBundle {
    #[serde(rename = "baseEntitlementAndAddOns")]
    pub base_entitlement_and_add_ons: Vec<models::Subscription>,
}

impl BulkSubscriptionsBundle {
    pub fn new(base_entitlement_and_add_ons: Vec<models::Subscription>) -> BulkSubscriptionsBundle {
        BulkSubscriptionsBundle {
            base_entitlement_and_add_ons,
        }
    }
}

