/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bundle {
    #[serde(rename = "accountId")]
    pub account_id: uuid::Uuid,
    #[serde(rename = "bundleId", skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<uuid::Uuid>,
    #[serde(rename = "externalKey", skip_serializing_if = "Option::is_none")]
    pub external_key: Option<String>,
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::Subscription>>,
    #[serde(rename = "timeline", skip_serializing_if = "Option::is_none")]
    pub timeline: Option<Box<models::BundleTimeline>>,
    #[serde(rename = "auditLogs", skip_serializing_if = "Option::is_none")]
    pub audit_logs: Option<Vec<models::AuditLog>>,
}

impl Bundle {
    pub fn new(account_id: uuid::Uuid) -> Bundle {
        Bundle {
            account_id,
            bundle_id: None,
            external_key: None,
            subscriptions: None,
            timeline: None,
            audit_logs: None,
        }
    }
}

