/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComboHostedPaymentPage {
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<models::Account>>,
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<Box<models::PaymentMethod>>,
    #[serde(rename = "hostedPaymentPageFields", skip_serializing_if = "Option::is_none")]
    pub hosted_payment_page_fields: Option<Box<models::HostedPaymentPageFields>>,
    #[serde(rename = "paymentMethodPluginProperties", skip_serializing_if = "Option::is_none")]
    pub payment_method_plugin_properties: Option<Vec<models::PluginProperty>>,
    #[serde(rename = "auditLogs", skip_serializing_if = "Option::is_none")]
    pub audit_logs: Option<Vec<models::AuditLog>>,
}

impl ComboHostedPaymentPage {
    pub fn new() -> ComboHostedPaymentPage {
        ComboHostedPaymentPage {
            account: None,
            payment_method: None,
            hosted_payment_page_fields: None,
            payment_method_plugin_properties: None,
            audit_logs: None,
        }
    }
}

