/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Duration {
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Unit>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
}

impl Duration {
    pub fn new() -> Duration {
        Duration {
            unit: None,
            number: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "DAYS")]
    Days,
    #[serde(rename = "WEEKS")]
    Weeks,
    #[serde(rename = "MONTHS")]
    Months,
    #[serde(rename = "YEARS")]
    Years,
    #[serde(rename = "UNLIMITED")]
    Unlimited,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Days
    }
}

