/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostedPaymentPageFields {
    #[serde(rename = "formFields", skip_serializing_if = "Option::is_none")]
    pub form_fields: Option<Vec<models::PluginProperty>>,
}

impl HostedPaymentPageFields {
    pub fn new() -> HostedPaymentPageFields {
        HostedPaymentPageFields {
            form_fields: None,
        }
    }
}

