/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostedPaymentPageFormDescriptor {
    #[serde(rename = "kbAccountId", skip_serializing_if = "Option::is_none")]
    pub kb_account_id: Option<uuid::Uuid>,
    #[serde(rename = "formMethod", skip_serializing_if = "Option::is_none")]
    pub form_method: Option<String>,
    #[serde(rename = "formUrl", skip_serializing_if = "Option::is_none")]
    pub form_url: Option<String>,
    #[serde(rename = "formFields", skip_serializing_if = "Option::is_none")]
    pub form_fields: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "auditLogs", skip_serializing_if = "Option::is_none")]
    pub audit_logs: Option<Vec<models::AuditLog>>,
}

impl HostedPaymentPageFormDescriptor {
    pub fn new() -> HostedPaymentPageFormDescriptor {
        HostedPaymentPageFormDescriptor {
            kb_account_id: None,
            form_method: None,
            form_url: None,
            form_fields: None,
            properties: None,
            audit_logs: None,
        }
    }
}

