/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeCommand {
    #[serde(rename = "isSystemCommandType", skip_serializing_if = "Option::is_none")]
    pub is_system_command_type: Option<bool>,
    #[serde(rename = "nodeCommandType", skip_serializing_if = "Option::is_none")]
    pub node_command_type: Option<String>,
    #[serde(rename = "nodeCommandProperties", skip_serializing_if = "Option::is_none")]
    pub node_command_properties: Option<Vec<models::NodeCommandProperty>>,
}

impl NodeCommand {
    pub fn new() -> NodeCommand {
        NodeCommand {
            is_system_command_type: None,
            node_command_type: None,
            node_command_properties: None,
        }
    }
}

