/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Overdue {
    #[serde(rename = "initialReevaluationInterval", skip_serializing_if = "Option::is_none")]
    pub initial_reevaluation_interval: Option<i32>,
    #[serde(rename = "overdueStates", skip_serializing_if = "Option::is_none")]
    pub overdue_states: Option<Vec<models::OverdueStateConfig>>,
}

impl Overdue {
    pub fn new() -> Overdue {
        Overdue {
            initial_reevaluation_interval: None,
            overdue_states: None,
        }
    }
}

