/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginProperty {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "isUpdatable", skip_serializing_if = "Option::is_none")]
    pub is_updatable: Option<bool>,
}

impl PluginProperty {
    pub fn new() -> PluginProperty {
        PluginProperty {
            key: None,
            value: None,
            is_updatable: None,
        }
    }
}

