/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subject {
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<String>,
    #[serde(rename = "isAuthenticated", skip_serializing_if = "Option::is_none")]
    pub is_authenticated: Option<bool>,
    #[serde(rename = "isRemembered", skip_serializing_if = "Option::is_none")]
    pub is_remembered: Option<bool>,
    #[serde(rename = "session", skip_serializing_if = "Option::is_none")]
    pub session: Option<Box<models::Session>>,
}

impl Subject {
    pub fn new() -> Subject {
        Subject {
            principal: None,
            is_authenticated: None,
            is_remembered: None,
            session: None,
        }
    }
}

