/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagDefinition {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "isControlTag", skip_serializing_if = "Option::is_none")]
    pub is_control_tag: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "applicableObjectTypes", skip_serializing_if = "Option::is_none")]
    pub applicable_object_types: Option<std::collections::HashSet<ApplicableObjectTypes>>,
    #[serde(rename = "auditLogs", skip_serializing_if = "Option::is_none")]
    pub audit_logs: Option<Vec<models::AuditLog>>,
}

impl TagDefinition {
    pub fn new(name: String, description: String) -> TagDefinition {
        TagDefinition {
            id: None,
            is_control_tag: None,
            name,
            description,
            applicable_object_types: None,
            audit_logs: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicableObjectTypes {
    #[serde(rename = "ACCOUNT")]
    Account,
    #[serde(rename = "ACCOUNT_EMAIL")]
    AccountEmail,
    #[serde(rename = "BLOCKING_STATES")]
    BlockingStates,
    #[serde(rename = "BUNDLE")]
    Bundle,
    #[serde(rename = "CUSTOM_FIELD")]
    CustomField,
    #[serde(rename = "INVOICE")]
    Invoice,
    #[serde(rename = "PAYMENT")]
    Payment,
    #[serde(rename = "TRANSACTION")]
    Transaction,
    #[serde(rename = "INVOICE_ITEM")]
    InvoiceItem,
    #[serde(rename = "INVOICE_PAYMENT")]
    InvoicePayment,
    #[serde(rename = "SUBSCRIPTION")]
    Subscription,
    #[serde(rename = "SUBSCRIPTION_EVENT")]
    SubscriptionEvent,
    #[serde(rename = "SERVICE_BROADCAST")]
    ServiceBroadcast,
    #[serde(rename = "PAYMENT_ATTEMPT")]
    PaymentAttempt,
    #[serde(rename = "PAYMENT_METHOD")]
    PaymentMethod,
    #[serde(rename = "TAG")]
    Tag,
    #[serde(rename = "TAG_DEFINITION")]
    TagDefinition,
    #[serde(rename = "TENANT")]
    Tenant,
    #[serde(rename = "TENANT_KVS")]
    TenantKvs,
}

impl Default for ApplicableObjectTypes {
    fn default() -> ApplicableObjectTypes {
        Self::Account
    }
}

