/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tier {
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Vec<models::Limit>>,
    #[serde(rename = "fixedPrice", skip_serializing_if = "Option::is_none")]
    pub fixed_price: Option<Vec<models::Price>>,
    #[serde(rename = "recurringPrice", skip_serializing_if = "Option::is_none")]
    pub recurring_price: Option<Vec<models::Price>>,
    #[serde(rename = "blocks", skip_serializing_if = "Option::is_none")]
    pub blocks: Option<Vec<models::TieredBlock>>,
}

impl Tier {
    pub fn new() -> Tier {
        Tier {
            limits: None,
            fixed_price: None,
            recurring_price: None,
            blocks: None,
        }
    }
}

