/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnitUsageRecord {
    #[serde(rename = "unitType", skip_serializing_if = "Option::is_none")]
    pub unit_type: Option<String>,
    #[serde(rename = "usageRecords", skip_serializing_if = "Option::is_none")]
    pub usage_records: Option<Vec<models::UsageRecord>>,
}

impl UnitUsageRecord {
    pub fn new() -> UnitUsageRecord {
        UnitUsageRecord {
            unit_type: None,
            usage_records: None,
        }
    }
}

