/*
 * Kill Bill
 *
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageRecord {
    #[serde(rename = "recordDate", skip_serializing_if = "Option::is_none")]
    pub record_date: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
}

impl UsageRecord {
    pub fn new() -> UsageRecord {
        UsageRecord {
            record_date: None,
            amount: None,
        }
    }
}

